// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vurdalakov.LanguageLocker64
{
    internal sealed partial class Vsix
    {
        public const string Id = "Vurdalakov.LanguageLocker64.c1524243-c7a8-49e9-bdac-fba459cff3f5";
        public const string Name = "Language Locker x64";
        public const string Description = @"Prevents switching of keyboard layout (e.g. English to Russian) while working in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Vurdalakov";
        public const string Tags = "";
    }
}
