// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vurdalakov.LanguageLocker64
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LanguageLocker64String = "e3611a09-4b70-4447-8636-6e31127f74e5";
        public static Guid LanguageLocker64 = new Guid(LanguageLocker64String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LanguageLockerMenuGroup = 0x0001;
        public const int LockLanguageCommand = 0x0100;
    }
}